[package]
name = "mnemonic-tools-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
mnemonic-tools = { path = "../mnemonic-tools" }
rand = "0.8.5"
